version: "3"
services:
  notif-ms:
    build: ./
    restart: on-failure
    ports:
      - 9000:9000
    depends_on:
      - notif-db
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - REDIS_URL="notif-db:6379"

  notif-db:
    image: redis:5-alpine
