version: "3"
services:
  notification-ms:
    container_name: notification-ms
    build: ./
    restart: on-failure
    ports:
      - 9000:9000
    depends_on:
      - notification-db
      - notification-gorush
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - REDIS_URL="${NOTIF_IP}:9001"
      - GORUSH_HOST="${NOTIF_IP}:9002"

  notification-db:
    image: redis:5-alpine
    container_name: notification-db
    ports:
      - 9001:6379

  notification-gorush:
    image: appleboy/gorush
    container_name: notification-gorush
    ports:
      - 9002:8088
    command:
      - git clone https://github.com/clifford-un/notification-ms -c develop
      - gorush -c ${PWD}/notification-ms/gorush_config.yml:/config.yml