version: "3"
services:
  notif-ms:
    build: ./
    restart: on-failure
    ports:
      - 9000:9000
    depends_on:
      - notif-db
      - notif-gr
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - REDIS_URL="notif-db:6379"
      - GORUSH_HOST="notif-gr:8088"

  notif-db:
    image: redis:5-alpine
    ports:
      - 9001:6379

  notif-gr:
    image: appleboy/gorush
    ports:
      - 9002:8088
    entrypoint: 'gorush -k "${FIREBASE_API_KEY}"'